class TokenType:
    API_TOKEN = "API_TOKEN"
    COOKIE_TOKEN = "COOKIE_TOKEN"
    REFRESH_TOKEN = "REFRESH_TOKEN"
    ACCESS_TOKEN = "ACCESS_TOKEN"
    RESET_PASSWORD = "RESET_PASSWORD"
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
